repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black

- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
    - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
    - id: flake8
